// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountOut
 */
export type AccountOut = {
    /**
     * Account Uuid
     */
    account_uuid: string;
    /**
     * Available Kop
     */
    available_kop: number;
    /**
     * On Hold Kop
     */
    on_hold_kop: number;
    /**
     * Total Kop
     */
    total_kop: number;
};

/**
 * AnswerIn
 */
export type AnswerIn = {
    /**
     * Test Question Uuid
     */
    test_question_uuid: string;
    /**
     * Selected Indices
     */
    selected_indices: Array<number>;
};

/**
 * ApplicationDetailOut
 */
export type ApplicationDetailOut = {
    /**
     * Application Uuid
     */
    application_uuid: string;
    /**
     * Vacancy Uuid
     */
    vacancy_uuid: string;
    /**
     * User Uuid
     */
    user_uuid: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Timeline
     */
    timeline: Array<TimelineEventOut>;
};

/**
 * ApplicationOut
 */
export type ApplicationOut = {
    /**
     * Application Uuid
     */
    application_uuid: string;
    /**
     * Vacancy Uuid
     */
    vacancy_uuid: string;
    /**
     * User Uuid
     */
    user_uuid: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AttemptOut
 */
export type AttemptOut = {
    /**
     * Test Attempt Uuid
     */
    test_attempt_uuid: string;
    /**
     * Test Uuid
     */
    test_uuid: string;
    /**
     * Status
     */
    status: string;
    /**
     * Correct Count
     */
    correct_count: number;
    /**
     * Score Pct
     */
    score_pct: number;
    /**
     * Passed
     */
    passed: boolean;
    /**
     * Cooldown Until
     */
    cooldown_until: string | null;
};

/**
 * AttemptWithQuestionsOut
 */
export type AttemptWithQuestionsOut = {
    /**
     * Test Attempt Uuid
     */
    test_attempt_uuid: string;
    /**
     * Test Uuid
     */
    test_uuid: string;
    /**
     * Status
     */
    status: string;
    /**
     * Correct Count
     */
    correct_count: number;
    /**
     * Score Pct
     */
    score_pct: number;
    /**
     * Passed
     */
    passed: boolean;
    /**
     * Cooldown Until
     */
    cooldown_until: string | null;
    /**
     * Questions
     */
    questions: Array<QuestionOut>;
};

/**
 * Body_upload_document_api_v1_documents_post
 */
export type BodyUploadDocumentApiV1DocumentsPost = {
    kind: DocumentKind;
    /**
     * File
     */
    file: string;
};

/**
 * CandidateEntryIn
 */
export type CandidateEntryIn = {
    /**
     * List
     */
    list: 'shortlist' | 'reserve' | 'blacklist';
    /**
     * Note
     */
    note?: string | null;
};

/**
 * CandidateEntryOut
 */
export type CandidateEntryOut = {
    /**
     * Entry Uuid
     */
    entry_uuid: string;
    /**
     * Company Uuid
     */
    company_uuid: string;
    /**
     * User Uuid
     */
    user_uuid: string;
    /**
     * List
     */
    list: string;
    /**
     * Note
     */
    note: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CompanyApplicationOut
 * Строка отклика для компании: заявка + профиль кандидата (без KYC-контента).
 */
export type CompanyApplicationOut = {
    /**
     * Application Uuid
     */
    application_uuid: string;
    /**
     * Vacancy Uuid
     */
    vacancy_uuid: string;
    /**
     * User Uuid
     */
    user_uuid: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * User Name
     */
    user_name: string | null;
    vacancy: VacancyOut;
    /**
     * Company Test Passed
     */
    company_test_passed?: boolean;
};

/**
 * CompanyCreateIn
 */
export type CompanyCreateIn = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CompanyOut
 */
export type CompanyOut = {
    /**
     * Company Uuid
     */
    company_uuid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CompanyTestItemOut
 * Строка списка тестов в кабинете организации.
 */
export type CompanyTestItemOut = {
    /**
     * Test Uuid
     */
    test_uuid: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Company Uuid
     */
    company_uuid: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Topic
     */
    topic: string;
    /**
     * Min Correct
     */
    min_correct: number;
    /**
     * Status
     */
    status: string;
    /**
     * Reject Reason
     */
    reject_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Questions Count
     */
    questions_count: number;
    /**
     * Passed Count
     */
    passed_count: number;
};

/**
 * CompanyUpdateIn
 */
export type CompanyUpdateIn = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * DocumentKind
 */
export type DocumentKind = 'passport' | 'selfie_with_passport' | 'medbook' | 'diploma' | 'payment_proof';

/**
 * DocumentOut
 * Метаданные документа. storage_key наружу не отдаётся (skill s3-documents-kyc).
 */
export type DocumentOut = {
    /**
     * Document Uuid
     */
    document_uuid: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Status
     */
    status: string;
    /**
     * Mime
     */
    mime: string;
    /**
     * Size Bytes
     */
    size_bytes: number;
    /**
     * Reject Reason
     */
    reject_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * FeedItemOut
 * Карточка ленты: вакансия + витринные поля компании и заполняемость.
 */
export type FeedItemOut = {
    /**
     * Vacancy Uuid
     */
    vacancy_uuid: string;
    /**
     * Company Uuid
     */
    company_uuid: string;
    /**
     * Filial Uuid
     */
    filial_uuid: string;
    /**
     * Role Name
     */
    role_name: string;
    /**
     * Event Title
     */
    event_title: string;
    /**
     * Starts At
     */
    starts_at: string;
    /**
     * Ends At
     */
    ends_at: string;
    /**
     * Venue Address
     */
    venue_address: string;
    /**
     * Lat
     */
    lat: number | null;
    /**
     * Lon
     */
    lon: number | null;
    /**
     * Pay Hour Kop
     */
    pay_hour_kop: number;
    /**
     * Pay Total Kop
     */
    pay_total_kop: number;
    /**
     * Slots
     */
    slots: number;
    /**
     * Urgent
     */
    urgent: boolean;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Requirements
     */
    requirements: Array<string>;
    /**
     * Status
     */
    status: string;
    /**
     * Reject Reason
     */
    reject_reason: string | null;
    /**
     * Archived At
     */
    archived_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Company Name
     */
    company_name: string;
    /**
     * Company Rating
     */
    company_rating?: number | null;
    /**
     * Filled
     */
    filled?: number;
};

/**
 * FilialCreateIn
 */
export type FilialCreateIn = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address: string;
    /**
     * Lat
     */
    lat?: number | null;
    /**
     * Lon
     */
    lon?: number | null;
};

/**
 * FilialOut
 */
export type FilialOut = {
    /**
     * Filial Uuid
     */
    filial_uuid: string;
    /**
     * Company Uuid
     */
    company_uuid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address: string;
    /**
     * Lat
     */
    lat: number | null;
    /**
     * Lon
     */
    lon: number | null;
};

/**
 * FilialUpdateIn
 */
export type FilialUpdateIn = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Lat
     */
    lat?: number | null;
    /**
     * Lon
     */
    lon?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InviteCreateIn
 */
export type InviteCreateIn = {
    /**
     * Role
     */
    role: 'manager' | 'coordinator' | 'staff';
    /**
     * Expires In
     */
    expires_in: '24h' | '7d' | '30d';
    /**
     * Max Uses
     */
    max_uses: number;
    /**
     * Filial Uuid
     */
    filial_uuid?: string | null;
};

/**
 * InviteOut
 */
export type InviteOut = {
    /**
     * Invite Link Uuid
     */
    invite_link_uuid: string;
    /**
     * Code
     */
    code: string;
    /**
     * Role
     */
    role: string;
    /**
     * Filial Uuid
     */
    filial_uuid: string | null;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Max Uses
     */
    max_uses: number;
    /**
     * Uses Count
     */
    uses_count: number;
    /**
     * Active
     */
    active: boolean;
};

/**
 * MeOut
 */
export type MeOut = {
    /**
     * User Uuid
     */
    user_uuid: string;
    /**
     * Phone
     */
    phone: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * City
     */
    city: string | null;
    /**
     * Platform Role
     */
    platform_role: string;
    /**
     * Pd Consent At
     */
    pd_consent_at: string | null;
};

/**
 * ModerateIn
 */
export type ModerateIn = {
    /**
     * Action
     */
    action: 'approve' | 'reject';
    /**
     * Reason
     */
    reason?: string | null;
};

/**
 * MyApplicationOut
 * Карточка «Мои заявки»: заявка + смена + компания.
 */
export type MyApplicationOut = {
    /**
     * Application Uuid
     */
    application_uuid: string;
    /**
     * Vacancy Uuid
     */
    vacancy_uuid: string;
    /**
     * User Uuid
     */
    user_uuid: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    vacancy: VacancyOut;
    /**
     * Company Name
     */
    company_name: string;
};

/**
 * MyCompanyOut
 */
export type MyCompanyOut = {
    company: CompanyOut;
    /**
     * Company Role
     */
    company_role: string;
};

/**
 * MyResultOut
 */
export type MyResultOut = {
    /**
     * Passed
     */
    passed: boolean;
    /**
     * Score Pct
     */
    score_pct: number;
};

/**
 * OperationOut
 */
export type OperationOut = {
    /**
     * Ledger Entry Uuid
     */
    ledger_entry_uuid: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Amount Kop
     */
    amount_kop: number;
    /**
     * Direction
     */
    direction: 'in' | 'out';
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * OtpRequestIn
 */
export type OtpRequestIn = {
    /**
     * Phone
     */
    phone: string;
};

/**
 * OtpVerifyIn
 */
export type OtpVerifyIn = {
    /**
     * Phone
     */
    phone: string;
    /**
     * Code
     */
    code: string;
};

/**
 * QuestionIn
 */
export type QuestionIn = {
    /**
     * Text
     */
    text: string;
    /**
     * Multi
     */
    multi?: boolean;
    /**
     * Options
     */
    options: Array<string>;
    /**
     * Correct Indices
     */
    correct_indices: Array<number>;
};

/**
 * QuestionOut
 * Вопрос для прохождения — без correct_indices (skill real-data-only §ответы).
 */
export type QuestionOut = {
    /**
     * Test Question Uuid
     */
    test_question_uuid: string;
    /**
     * Position
     */
    position: number;
    /**
     * Text
     */
    text: string;
    /**
     * Multi
     */
    multi: boolean;
    /**
     * Options
     */
    options: Array<string>;
};

/**
 * RefreshIn
 */
export type RefreshIn = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * StatusChangeIn
 */
export type StatusChangeIn = {
    /**
     * Action
     */
    action: 'confirm' | 'reserve';
};

/**
 * TeamMemberOut
 */
export type TeamMemberOut = {
    /**
     * Team Member Uuid
     */
    team_member_uuid: string;
    /**
     * User Uuid
     */
    user_uuid: string;
    /**
     * Company Role
     */
    company_role: string;
    /**
     * Filial Uuid
     */
    filial_uuid: string | null;
    /**
     * Email
     */
    email: string | null;
    /**
     * Perm Create
     */
    perm_create: boolean;
    /**
     * Perm Hire
     */
    perm_hire: boolean;
    /**
     * Perm Finance
     */
    perm_finance: boolean;
    /**
     * Perm Invite
     */
    perm_invite: boolean;
};

/**
 * TeamPermissionsPatchIn
 */
export type TeamPermissionsPatchIn = {
    /**
     * Perm Create
     */
    perm_create?: boolean | null;
    /**
     * Perm Hire
     */
    perm_hire?: boolean | null;
    /**
     * Perm Finance
     */
    perm_finance?: boolean | null;
    /**
     * Perm Invite
     */
    perm_invite?: boolean | null;
};

/**
 * TestCreateIn
 */
export type TestCreateIn = {
    /**
     * Title
     */
    title: string;
    /**
     * Topic
     */
    topic: string;
    /**
     * Min Correct
     */
    min_correct: number;
    /**
     * Questions
     */
    questions: Array<QuestionIn>;
};

/**
 * TestListItemOut
 * Строка каталога тестов: прогресс пользователя поверх теста.
 */
export type TestListItemOut = {
    /**
     * Test Uuid
     */
    test_uuid: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Company Uuid
     */
    company_uuid: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Topic
     */
    topic: string;
    /**
     * Min Correct
     */
    min_correct: number;
    /**
     * Status
     */
    status: string;
    /**
     * Reject Reason
     */
    reject_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Company Name
     */
    company_name?: string | null;
    /**
     * Questions Count
     */
    questions_count: number;
    my_result?: MyResultOut | null;
    /**
     * Cooldown Until
     */
    cooldown_until?: string | null;
};

/**
 * TestOut
 */
export type TestOut = {
    /**
     * Test Uuid
     */
    test_uuid: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Company Uuid
     */
    company_uuid: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Topic
     */
    topic: string;
    /**
     * Min Correct
     */
    min_correct: number;
    /**
     * Status
     */
    status: string;
    /**
     * Reject Reason
     */
    reject_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TimelineEventOut
 */
export type TimelineEventOut = {
    /**
     * Kind
     */
    kind: string;
    /**
     * Occurred At
     */
    occurred_at: string;
};

/**
 * TokensOut
 */
export type TokensOut = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Is New User
     */
    is_new_user?: boolean;
};

/**
 * TopupCreateIn
 */
export type TopupCreateIn = {
    /**
     * Amount Kop
     */
    amount_kop: number;
    /**
     * Proof Document Uuid
     */
    proof_document_uuid: string;
    /**
     * Payment Details
     */
    payment_details?: string | null;
};

/**
 * TopupRequestOut
 */
export type TopupRequestOut = {
    /**
     * Topup Request Uuid
     */
    topup_request_uuid: string;
    /**
     * Account Uuid
     */
    account_uuid: string;
    /**
     * Amount Kop
     */
    amount_kop: number;
    /**
     * Proof Document Uuid
     */
    proof_document_uuid: string;
    /**
     * Payment Details
     */
    payment_details: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Reject Reason
     */
    reject_reason: string | null;
    /**
     * Reviewed At
     */
    reviewed_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TopupResolveIn
 */
export type TopupResolveIn = {
    /**
     * Action
     */
    action: 'approve' | 'reject';
    /**
     * Reason
     */
    reason?: string | null;
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * User Uuid
     */
    user_uuid: string;
    /**
     * Phone
     */
    phone: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * City
     */
    city: string | null;
    /**
     * Platform Role
     */
    platform_role: string;
    /**
     * Desired Roles
     */
    desired_roles: Array<string>;
    /**
     * Pd Consent At
     */
    pd_consent_at: string | null;
};

/**
 * UserUpdateIn
 */
export type UserUpdateIn = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Desired Roles
     */
    desired_roles?: Array<string> | null;
};

/**
 * VacancyCreateIn
 */
export type VacancyCreateIn = {
    /**
     * Filial Uuid
     */
    filial_uuid: string;
    /**
     * Role Name
     */
    role_name: string;
    /**
     * Event Title
     */
    event_title: string;
    /**
     * Starts At
     */
    starts_at: string;
    /**
     * Ends At
     */
    ends_at: string;
    /**
     * Venue Address
     */
    venue_address: string;
    /**
     * Lat
     */
    lat?: number | null;
    /**
     * Lon
     */
    lon?: number | null;
    /**
     * Pay Hour Kop
     */
    pay_hour_kop: number;
    /**
     * Slots
     */
    slots: number;
    /**
     * Urgent
     */
    urgent?: boolean;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Requirements
     */
    requirements?: Array<string>;
};

/**
 * VacancyOut
 */
export type VacancyOut = {
    /**
     * Vacancy Uuid
     */
    vacancy_uuid: string;
    /**
     * Company Uuid
     */
    company_uuid: string;
    /**
     * Filial Uuid
     */
    filial_uuid: string;
    /**
     * Role Name
     */
    role_name: string;
    /**
     * Event Title
     */
    event_title: string;
    /**
     * Starts At
     */
    starts_at: string;
    /**
     * Ends At
     */
    ends_at: string;
    /**
     * Venue Address
     */
    venue_address: string;
    /**
     * Lat
     */
    lat: number | null;
    /**
     * Lon
     */
    lon: number | null;
    /**
     * Pay Hour Kop
     */
    pay_hour_kop: number;
    /**
     * Pay Total Kop
     */
    pay_total_kop: number;
    /**
     * Slots
     */
    slots: number;
    /**
     * Urgent
     */
    urgent: boolean;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Requirements
     */
    requirements: Array<string>;
    /**
     * Status
     */
    status: string;
    /**
     * Reject Reason
     */
    reject_reason: string | null;
    /**
     * Archived At
     */
    archived_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * VacancyUpdateIn
 */
export type VacancyUpdateIn = {
    /**
     * Role Name
     */
    role_name?: string | null;
    /**
     * Event Title
     */
    event_title?: string | null;
    /**
     * Starts At
     */
    starts_at?: string | null;
    /**
     * Ends At
     */
    ends_at?: string | null;
    /**
     * Venue Address
     */
    venue_address?: string | null;
    /**
     * Lat
     */
    lat?: number | null;
    /**
     * Lon
     */
    lon?: number | null;
    /**
     * Pay Hour Kop
     */
    pay_hour_kop?: number | null;
    /**
     * Slots
     */
    slots?: number | null;
    /**
     * Urgent
     */
    urgent?: boolean | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Requirements
     */
    requirements?: Array<string> | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthApiV1HealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthApiV1HealthGetResponses = {
    /**
     * Response Health Api V1 Health Get
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthApiV1HealthGetResponse = HealthApiV1HealthGetResponses[keyof HealthApiV1HealthGetResponses];

export type RequestOtpApiV1AuthOtpRequestPostData = {
    body: OtpRequestIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/otp/request';
};

export type RequestOtpApiV1AuthOtpRequestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestOtpApiV1AuthOtpRequestPostError = RequestOtpApiV1AuthOtpRequestPostErrors[keyof RequestOtpApiV1AuthOtpRequestPostErrors];

export type RequestOtpApiV1AuthOtpRequestPostResponses = {
    /**
     * Response Request Otp Api V1 Auth Otp Request Post
     * Successful Response
     */
    202: {
        [key: string]: unknown;
    };
};

export type RequestOtpApiV1AuthOtpRequestPostResponse = RequestOtpApiV1AuthOtpRequestPostResponses[keyof RequestOtpApiV1AuthOtpRequestPostResponses];

export type VerifyOtpApiV1AuthOtpVerifyPostData = {
    body: OtpVerifyIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/otp/verify';
};

export type VerifyOtpApiV1AuthOtpVerifyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyOtpApiV1AuthOtpVerifyPostError = VerifyOtpApiV1AuthOtpVerifyPostErrors[keyof VerifyOtpApiV1AuthOtpVerifyPostErrors];

export type VerifyOtpApiV1AuthOtpVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: TokensOut;
};

export type VerifyOtpApiV1AuthOtpVerifyPostResponse = VerifyOtpApiV1AuthOtpVerifyPostResponses[keyof VerifyOtpApiV1AuthOtpVerifyPostResponses];

export type RefreshApiV1AuthRefreshPostData = {
    body: RefreshIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshApiV1AuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshApiV1AuthRefreshPostError = RefreshApiV1AuthRefreshPostErrors[keyof RefreshApiV1AuthRefreshPostErrors];

export type RefreshApiV1AuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: TokensOut;
};

export type RefreshApiV1AuthRefreshPostResponse = RefreshApiV1AuthRefreshPostResponses[keyof RefreshApiV1AuthRefreshPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body: RefreshIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutApiV1AuthLogoutPostError = LogoutApiV1AuthLogoutPostErrors[keyof LogoutApiV1AuthLogoutPostErrors];

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiV1AuthLogoutPostResponse = LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type MeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type MeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: MeOut;
};

export type MeApiV1AuthMeGetResponse = MeApiV1AuthMeGetResponses[keyof MeApiV1AuthMeGetResponses];

export type ConsentApiV1AuthConsentPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/consent';
};

export type ConsentApiV1AuthConsentPostResponses = {
    /**
     * Successful Response
     */
    200: MeOut;
};

export type ConsentApiV1AuthConsentPostResponse = ConsentApiV1AuthConsentPostResponses[keyof ConsentApiV1AuthConsentPostResponses];

export type GetMeApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetMeApiV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type GetMeApiV1UsersMeGetResponse = GetMeApiV1UsersMeGetResponses[keyof GetMeApiV1UsersMeGetResponses];

export type UpdateMeApiV1UsersMePatchData = {
    body: UserUpdateIn;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateMeApiV1UsersMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMeApiV1UsersMePatchError = UpdateMeApiV1UsersMePatchErrors[keyof UpdateMeApiV1UsersMePatchErrors];

export type UpdateMeApiV1UsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type UpdateMeApiV1UsersMePatchResponse = UpdateMeApiV1UsersMePatchResponses[keyof UpdateMeApiV1UsersMePatchResponses];

export type UploadDocumentApiV1DocumentsPostData = {
    body: BodyUploadDocumentApiV1DocumentsPost;
    path?: never;
    query?: never;
    url: '/api/v1/documents';
};

export type UploadDocumentApiV1DocumentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDocumentApiV1DocumentsPostError = UploadDocumentApiV1DocumentsPostErrors[keyof UploadDocumentApiV1DocumentsPostErrors];

export type UploadDocumentApiV1DocumentsPostResponses = {
    /**
     * Successful Response
     */
    201: DocumentOut;
};

export type UploadDocumentApiV1DocumentsPostResponse = UploadDocumentApiV1DocumentsPostResponses[keyof UploadDocumentApiV1DocumentsPostResponses];

export type MyDocumentsApiV1DocumentsMyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/documents/my';
};

export type MyDocumentsApiV1DocumentsMyGetResponses = {
    /**
     * Response My Documents Api V1 Documents My Get
     * Successful Response
     */
    200: Array<DocumentOut>;
};

export type MyDocumentsApiV1DocumentsMyGetResponse = MyDocumentsApiV1DocumentsMyGetResponses[keyof MyDocumentsApiV1DocumentsMyGetResponses];

export type DocumentContentApiV1DocumentsDocumentUuidContentGetData = {
    body?: never;
    path: {
        /**
         * Document Uuid
         */
        document_uuid: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_uuid}/content';
};

export type DocumentContentApiV1DocumentsDocumentUuidContentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentContentApiV1DocumentsDocumentUuidContentGetError = DocumentContentApiV1DocumentsDocumentUuidContentGetErrors[keyof DocumentContentApiV1DocumentsDocumentUuidContentGetErrors];

export type DocumentContentApiV1DocumentsDocumentUuidContentGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateCompanyApiV1CompaniesPostData = {
    body: CompanyCreateIn;
    path?: never;
    query?: never;
    url: '/api/v1/companies';
};

export type CreateCompanyApiV1CompaniesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCompanyApiV1CompaniesPostError = CreateCompanyApiV1CompaniesPostErrors[keyof CreateCompanyApiV1CompaniesPostErrors];

export type CreateCompanyApiV1CompaniesPostResponses = {
    /**
     * Successful Response
     */
    201: CompanyOut;
};

export type CreateCompanyApiV1CompaniesPostResponse = CreateCompanyApiV1CompaniesPostResponses[keyof CreateCompanyApiV1CompaniesPostResponses];

export type MyCompaniesApiV1CompaniesMyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/companies/my';
};

export type MyCompaniesApiV1CompaniesMyGetResponses = {
    /**
     * Response My Companies Api V1 Companies My Get
     * Successful Response
     */
    200: Array<MyCompanyOut>;
};

export type MyCompaniesApiV1CompaniesMyGetResponse = MyCompaniesApiV1CompaniesMyGetResponses[keyof MyCompaniesApiV1CompaniesMyGetResponses];

export type GetCompanyApiV1CompaniesCompanyUuidGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}';
};

export type GetCompanyApiV1CompaniesCompanyUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCompanyApiV1CompaniesCompanyUuidGetError = GetCompanyApiV1CompaniesCompanyUuidGetErrors[keyof GetCompanyApiV1CompaniesCompanyUuidGetErrors];

export type GetCompanyApiV1CompaniesCompanyUuidGetResponses = {
    /**
     * Successful Response
     */
    200: CompanyOut;
};

export type GetCompanyApiV1CompaniesCompanyUuidGetResponse = GetCompanyApiV1CompaniesCompanyUuidGetResponses[keyof GetCompanyApiV1CompaniesCompanyUuidGetResponses];

export type UpdateCompanyApiV1CompaniesCompanyUuidPatchData = {
    body: CompanyUpdateIn;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}';
};

export type UpdateCompanyApiV1CompaniesCompanyUuidPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCompanyApiV1CompaniesCompanyUuidPatchError = UpdateCompanyApiV1CompaniesCompanyUuidPatchErrors[keyof UpdateCompanyApiV1CompaniesCompanyUuidPatchErrors];

export type UpdateCompanyApiV1CompaniesCompanyUuidPatchResponses = {
    /**
     * Successful Response
     */
    200: CompanyOut;
};

export type UpdateCompanyApiV1CompaniesCompanyUuidPatchResponse = UpdateCompanyApiV1CompaniesCompanyUuidPatchResponses[keyof UpdateCompanyApiV1CompaniesCompanyUuidPatchResponses];

export type ListTeamApiV1CompaniesCompanyUuidTeamGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/team';
};

export type ListTeamApiV1CompaniesCompanyUuidTeamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTeamApiV1CompaniesCompanyUuidTeamGetError = ListTeamApiV1CompaniesCompanyUuidTeamGetErrors[keyof ListTeamApiV1CompaniesCompanyUuidTeamGetErrors];

export type ListTeamApiV1CompaniesCompanyUuidTeamGetResponses = {
    /**
     * Response List Team Api V1 Companies  Company Uuid  Team Get
     * Successful Response
     */
    200: Array<TeamMemberOut>;
};

export type ListTeamApiV1CompaniesCompanyUuidTeamGetResponse = ListTeamApiV1CompaniesCompanyUuidTeamGetResponses[keyof ListTeamApiV1CompaniesCompanyUuidTeamGetResponses];

export type ListFilialsApiV1CompaniesCompanyUuidFilialsGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/filials';
};

export type ListFilialsApiV1CompaniesCompanyUuidFilialsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFilialsApiV1CompaniesCompanyUuidFilialsGetError = ListFilialsApiV1CompaniesCompanyUuidFilialsGetErrors[keyof ListFilialsApiV1CompaniesCompanyUuidFilialsGetErrors];

export type ListFilialsApiV1CompaniesCompanyUuidFilialsGetResponses = {
    /**
     * Response List Filials Api V1 Companies  Company Uuid  Filials Get
     * Successful Response
     */
    200: Array<FilialOut>;
};

export type ListFilialsApiV1CompaniesCompanyUuidFilialsGetResponse = ListFilialsApiV1CompaniesCompanyUuidFilialsGetResponses[keyof ListFilialsApiV1CompaniesCompanyUuidFilialsGetResponses];

export type CreateFilialApiV1CompaniesCompanyUuidFilialsPostData = {
    body: FilialCreateIn;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/filials';
};

export type CreateFilialApiV1CompaniesCompanyUuidFilialsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFilialApiV1CompaniesCompanyUuidFilialsPostError = CreateFilialApiV1CompaniesCompanyUuidFilialsPostErrors[keyof CreateFilialApiV1CompaniesCompanyUuidFilialsPostErrors];

export type CreateFilialApiV1CompaniesCompanyUuidFilialsPostResponses = {
    /**
     * Successful Response
     */
    201: FilialOut;
};

export type CreateFilialApiV1CompaniesCompanyUuidFilialsPostResponse = CreateFilialApiV1CompaniesCompanyUuidFilialsPostResponses[keyof CreateFilialApiV1CompaniesCompanyUuidFilialsPostResponses];

export type DeleteFilialApiV1FilialsFilialUuidDeleteData = {
    body?: never;
    path: {
        /**
         * Filial Uuid
         */
        filial_uuid: string;
    };
    query?: never;
    url: '/api/v1/filials/{filial_uuid}';
};

export type DeleteFilialApiV1FilialsFilialUuidDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFilialApiV1FilialsFilialUuidDeleteError = DeleteFilialApiV1FilialsFilialUuidDeleteErrors[keyof DeleteFilialApiV1FilialsFilialUuidDeleteErrors];

export type DeleteFilialApiV1FilialsFilialUuidDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteFilialApiV1FilialsFilialUuidDeleteResponse = DeleteFilialApiV1FilialsFilialUuidDeleteResponses[keyof DeleteFilialApiV1FilialsFilialUuidDeleteResponses];

export type UpdateFilialApiV1FilialsFilialUuidPatchData = {
    body: FilialUpdateIn;
    path: {
        /**
         * Filial Uuid
         */
        filial_uuid: string;
    };
    query?: never;
    url: '/api/v1/filials/{filial_uuid}';
};

export type UpdateFilialApiV1FilialsFilialUuidPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateFilialApiV1FilialsFilialUuidPatchError = UpdateFilialApiV1FilialsFilialUuidPatchErrors[keyof UpdateFilialApiV1FilialsFilialUuidPatchErrors];

export type UpdateFilialApiV1FilialsFilialUuidPatchResponses = {
    /**
     * Successful Response
     */
    200: FilialOut;
};

export type UpdateFilialApiV1FilialsFilialUuidPatchResponse = UpdateFilialApiV1FilialsFilialUuidPatchResponses[keyof UpdateFilialApiV1FilialsFilialUuidPatchResponses];

export type UpdatePermissionsApiV1TeamMembersTeamMemberUuidPermissionsPatchData = {
    body: TeamPermissionsPatchIn;
    path: {
        /**
         * Team Member Uuid
         */
        team_member_uuid: string;
    };
    query?: never;
    url: '/api/v1/team-members/{team_member_uuid}/permissions';
};

export type UpdatePermissionsApiV1TeamMembersTeamMemberUuidPermissionsPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePermissionsApiV1TeamMembersTeamMemberUuidPermissionsPatchError = UpdatePermissionsApiV1TeamMembersTeamMemberUuidPermissionsPatchErrors[keyof UpdatePermissionsApiV1TeamMembersTeamMemberUuidPermissionsPatchErrors];

export type UpdatePermissionsApiV1TeamMembersTeamMemberUuidPermissionsPatchResponses = {
    /**
     * Successful Response
     */
    200: TeamMemberOut;
};

export type UpdatePermissionsApiV1TeamMembersTeamMemberUuidPermissionsPatchResponse = UpdatePermissionsApiV1TeamMembersTeamMemberUuidPermissionsPatchResponses[keyof UpdatePermissionsApiV1TeamMembersTeamMemberUuidPermissionsPatchResponses];

export type RemoveMemberApiV1TeamMembersTeamMemberUuidDeleteData = {
    body?: never;
    path: {
        /**
         * Team Member Uuid
         */
        team_member_uuid: string;
    };
    query?: never;
    url: '/api/v1/team-members/{team_member_uuid}';
};

export type RemoveMemberApiV1TeamMembersTeamMemberUuidDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveMemberApiV1TeamMembersTeamMemberUuidDeleteError = RemoveMemberApiV1TeamMembersTeamMemberUuidDeleteErrors[keyof RemoveMemberApiV1TeamMembersTeamMemberUuidDeleteErrors];

export type RemoveMemberApiV1TeamMembersTeamMemberUuidDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveMemberApiV1TeamMembersTeamMemberUuidDeleteResponse = RemoveMemberApiV1TeamMembersTeamMemberUuidDeleteResponses[keyof RemoveMemberApiV1TeamMembersTeamMemberUuidDeleteResponses];

export type ListInvitesApiV1CompaniesCompanyUuidInvitesGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/invites';
};

export type ListInvitesApiV1CompaniesCompanyUuidInvitesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListInvitesApiV1CompaniesCompanyUuidInvitesGetError = ListInvitesApiV1CompaniesCompanyUuidInvitesGetErrors[keyof ListInvitesApiV1CompaniesCompanyUuidInvitesGetErrors];

export type ListInvitesApiV1CompaniesCompanyUuidInvitesGetResponses = {
    /**
     * Response List Invites Api V1 Companies  Company Uuid  Invites Get
     * Successful Response
     */
    200: Array<InviteOut>;
};

export type ListInvitesApiV1CompaniesCompanyUuidInvitesGetResponse = ListInvitesApiV1CompaniesCompanyUuidInvitesGetResponses[keyof ListInvitesApiV1CompaniesCompanyUuidInvitesGetResponses];

export type CreateInviteApiV1CompaniesCompanyUuidInvitesPostData = {
    body: InviteCreateIn;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/invites';
};

export type CreateInviteApiV1CompaniesCompanyUuidInvitesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInviteApiV1CompaniesCompanyUuidInvitesPostError = CreateInviteApiV1CompaniesCompanyUuidInvitesPostErrors[keyof CreateInviteApiV1CompaniesCompanyUuidInvitesPostErrors];

export type CreateInviteApiV1CompaniesCompanyUuidInvitesPostResponses = {
    /**
     * Successful Response
     */
    201: InviteOut;
};

export type CreateInviteApiV1CompaniesCompanyUuidInvitesPostResponse = CreateInviteApiV1CompaniesCompanyUuidInvitesPostResponses[keyof CreateInviteApiV1CompaniesCompanyUuidInvitesPostResponses];

export type AcceptInviteApiV1InvitesCodeAcceptPostData = {
    body?: never;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/v1/invites/{code}/accept';
};

export type AcceptInviteApiV1InvitesCodeAcceptPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptInviteApiV1InvitesCodeAcceptPostError = AcceptInviteApiV1InvitesCodeAcceptPostErrors[keyof AcceptInviteApiV1InvitesCodeAcceptPostErrors];

export type AcceptInviteApiV1InvitesCodeAcceptPostResponses = {
    /**
     * Successful Response
     */
    201: TeamMemberOut;
};

export type AcceptInviteApiV1InvitesCodeAcceptPostResponse = AcceptInviteApiV1InvitesCodeAcceptPostResponses[keyof AcceptInviteApiV1InvitesCodeAcceptPostResponses];

export type RevokeInviteApiV1InvitesInviteLinkUuidRevokePostData = {
    body?: never;
    path: {
        /**
         * Invite Link Uuid
         */
        invite_link_uuid: string;
    };
    query?: never;
    url: '/api/v1/invites/{invite_link_uuid}/revoke';
};

export type RevokeInviteApiV1InvitesInviteLinkUuidRevokePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeInviteApiV1InvitesInviteLinkUuidRevokePostError = RevokeInviteApiV1InvitesInviteLinkUuidRevokePostErrors[keyof RevokeInviteApiV1InvitesInviteLinkUuidRevokePostErrors];

export type RevokeInviteApiV1InvitesInviteLinkUuidRevokePostResponses = {
    /**
     * Successful Response
     */
    200: InviteOut;
};

export type RevokeInviteApiV1InvitesInviteLinkUuidRevokePostResponse = RevokeInviteApiV1InvitesInviteLinkUuidRevokePostResponses[keyof RevokeInviteApiV1InvitesInviteLinkUuidRevokePostResponses];

export type CompanyAccountApiV1CompaniesCompanyUuidAccountGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/account';
};

export type CompanyAccountApiV1CompaniesCompanyUuidAccountGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompanyAccountApiV1CompaniesCompanyUuidAccountGetError = CompanyAccountApiV1CompaniesCompanyUuidAccountGetErrors[keyof CompanyAccountApiV1CompaniesCompanyUuidAccountGetErrors];

export type CompanyAccountApiV1CompaniesCompanyUuidAccountGetResponses = {
    /**
     * Successful Response
     */
    200: AccountOut;
};

export type CompanyAccountApiV1CompaniesCompanyUuidAccountGetResponse = CompanyAccountApiV1CompaniesCompanyUuidAccountGetResponses[keyof CompanyAccountApiV1CompaniesCompanyUuidAccountGetResponses];

export type CompanyOperationsApiV1CompaniesCompanyUuidAccountOperationsGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/account/operations';
};

export type CompanyOperationsApiV1CompaniesCompanyUuidAccountOperationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompanyOperationsApiV1CompaniesCompanyUuidAccountOperationsGetError = CompanyOperationsApiV1CompaniesCompanyUuidAccountOperationsGetErrors[keyof CompanyOperationsApiV1CompaniesCompanyUuidAccountOperationsGetErrors];

export type CompanyOperationsApiV1CompaniesCompanyUuidAccountOperationsGetResponses = {
    /**
     * Response Company Operations Api V1 Companies  Company Uuid  Account Operations Get
     * Successful Response
     */
    200: Array<OperationOut>;
};

export type CompanyOperationsApiV1CompaniesCompanyUuidAccountOperationsGetResponse = CompanyOperationsApiV1CompaniesCompanyUuidAccountOperationsGetResponses[keyof CompanyOperationsApiV1CompaniesCompanyUuidAccountOperationsGetResponses];

export type CreateTopupRequestApiV1CompaniesCompanyUuidTopupRequestsPostData = {
    body: TopupCreateIn;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/topup-requests';
};

export type CreateTopupRequestApiV1CompaniesCompanyUuidTopupRequestsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTopupRequestApiV1CompaniesCompanyUuidTopupRequestsPostError = CreateTopupRequestApiV1CompaniesCompanyUuidTopupRequestsPostErrors[keyof CreateTopupRequestApiV1CompaniesCompanyUuidTopupRequestsPostErrors];

export type CreateTopupRequestApiV1CompaniesCompanyUuidTopupRequestsPostResponses = {
    /**
     * Successful Response
     */
    201: TopupRequestOut;
};

export type CreateTopupRequestApiV1CompaniesCompanyUuidTopupRequestsPostResponse = CreateTopupRequestApiV1CompaniesCompanyUuidTopupRequestsPostResponses[keyof CreateTopupRequestApiV1CompaniesCompanyUuidTopupRequestsPostResponses];

export type AdminListTopupRequestsApiV1AdminTopupRequestsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/topup-requests';
};

export type AdminListTopupRequestsApiV1AdminTopupRequestsGetResponses = {
    /**
     * Response Admin List Topup Requests Api V1 Admin Topup Requests Get
     * Successful Response
     */
    200: Array<TopupRequestOut>;
};

export type AdminListTopupRequestsApiV1AdminTopupRequestsGetResponse = AdminListTopupRequestsApiV1AdminTopupRequestsGetResponses[keyof AdminListTopupRequestsApiV1AdminTopupRequestsGetResponses];

export type AdminResolveTopupApiV1AdminTopupRequestsTopupRequestUuidResolvePostData = {
    body: TopupResolveIn;
    path: {
        /**
         * Topup Request Uuid
         */
        topup_request_uuid: string;
    };
    query?: never;
    url: '/api/v1/admin/topup-requests/{topup_request_uuid}/resolve';
};

export type AdminResolveTopupApiV1AdminTopupRequestsTopupRequestUuidResolvePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminResolveTopupApiV1AdminTopupRequestsTopupRequestUuidResolvePostError = AdminResolveTopupApiV1AdminTopupRequestsTopupRequestUuidResolvePostErrors[keyof AdminResolveTopupApiV1AdminTopupRequestsTopupRequestUuidResolvePostErrors];

export type AdminResolveTopupApiV1AdminTopupRequestsTopupRequestUuidResolvePostResponses = {
    /**
     * Successful Response
     */
    200: TopupRequestOut;
};

export type AdminResolveTopupApiV1AdminTopupRequestsTopupRequestUuidResolvePostResponse = AdminResolveTopupApiV1AdminTopupRequestsTopupRequestUuidResolvePostResponses[keyof AdminResolveTopupApiV1AdminTopupRequestsTopupRequestUuidResolvePostResponses];

export type FeedApiV1VacanciesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Role
         */
        role?: string | null;
        /**
         * Date From
         */
        date_from?: string | null;
        /**
         * Date To
         */
        date_to?: string | null;
    };
    url: '/api/v1/vacancies';
};

export type FeedApiV1VacanciesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FeedApiV1VacanciesGetError = FeedApiV1VacanciesGetErrors[keyof FeedApiV1VacanciesGetErrors];

export type FeedApiV1VacanciesGetResponses = {
    /**
     * Response Feed Api V1 Vacancies Get
     * Successful Response
     */
    200: Array<FeedItemOut>;
};

export type FeedApiV1VacanciesGetResponse = FeedApiV1VacanciesGetResponses[keyof FeedApiV1VacanciesGetResponses];

export type VacancyDetailApiV1VacanciesVacancyUuidGetData = {
    body?: never;
    path: {
        /**
         * Vacancy Uuid
         */
        vacancy_uuid: string;
    };
    query?: never;
    url: '/api/v1/vacancies/{vacancy_uuid}';
};

export type VacancyDetailApiV1VacanciesVacancyUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VacancyDetailApiV1VacanciesVacancyUuidGetError = VacancyDetailApiV1VacanciesVacancyUuidGetErrors[keyof VacancyDetailApiV1VacanciesVacancyUuidGetErrors];

export type VacancyDetailApiV1VacanciesVacancyUuidGetResponses = {
    /**
     * Successful Response
     */
    200: VacancyOut;
};

export type VacancyDetailApiV1VacanciesVacancyUuidGetResponse = VacancyDetailApiV1VacanciesVacancyUuidGetResponses[keyof VacancyDetailApiV1VacanciesVacancyUuidGetResponses];

export type UpdateVacancyApiV1VacanciesVacancyUuidPatchData = {
    body: VacancyUpdateIn;
    path: {
        /**
         * Vacancy Uuid
         */
        vacancy_uuid: string;
    };
    query?: never;
    url: '/api/v1/vacancies/{vacancy_uuid}';
};

export type UpdateVacancyApiV1VacanciesVacancyUuidPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateVacancyApiV1VacanciesVacancyUuidPatchError = UpdateVacancyApiV1VacanciesVacancyUuidPatchErrors[keyof UpdateVacancyApiV1VacanciesVacancyUuidPatchErrors];

export type UpdateVacancyApiV1VacanciesVacancyUuidPatchResponses = {
    /**
     * Successful Response
     */
    200: VacancyOut;
};

export type UpdateVacancyApiV1VacanciesVacancyUuidPatchResponse = UpdateVacancyApiV1VacanciesVacancyUuidPatchResponses[keyof UpdateVacancyApiV1VacanciesVacancyUuidPatchResponses];

export type CompanyVacanciesApiV1CompaniesCompanyUuidVacanciesGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/vacancies';
};

export type CompanyVacanciesApiV1CompaniesCompanyUuidVacanciesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompanyVacanciesApiV1CompaniesCompanyUuidVacanciesGetError = CompanyVacanciesApiV1CompaniesCompanyUuidVacanciesGetErrors[keyof CompanyVacanciesApiV1CompaniesCompanyUuidVacanciesGetErrors];

export type CompanyVacanciesApiV1CompaniesCompanyUuidVacanciesGetResponses = {
    /**
     * Response Company Vacancies Api V1 Companies  Company Uuid  Vacancies Get
     * Successful Response
     */
    200: Array<VacancyOut>;
};

export type CompanyVacanciesApiV1CompaniesCompanyUuidVacanciesGetResponse = CompanyVacanciesApiV1CompaniesCompanyUuidVacanciesGetResponses[keyof CompanyVacanciesApiV1CompaniesCompanyUuidVacanciesGetResponses];

export type CreateVacancyApiV1CompaniesCompanyUuidVacanciesPostData = {
    body: VacancyCreateIn;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/vacancies';
};

export type CreateVacancyApiV1CompaniesCompanyUuidVacanciesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateVacancyApiV1CompaniesCompanyUuidVacanciesPostError = CreateVacancyApiV1CompaniesCompanyUuidVacanciesPostErrors[keyof CreateVacancyApiV1CompaniesCompanyUuidVacanciesPostErrors];

export type CreateVacancyApiV1CompaniesCompanyUuidVacanciesPostResponses = {
    /**
     * Successful Response
     */
    201: VacancyOut;
};

export type CreateVacancyApiV1CompaniesCompanyUuidVacanciesPostResponse = CreateVacancyApiV1CompaniesCompanyUuidVacanciesPostResponses[keyof CreateVacancyApiV1CompaniesCompanyUuidVacanciesPostResponses];

export type PublishVacancyApiV1VacanciesVacancyUuidPublishPostData = {
    body?: never;
    path: {
        /**
         * Vacancy Uuid
         */
        vacancy_uuid: string;
    };
    query?: never;
    url: '/api/v1/vacancies/{vacancy_uuid}/publish';
};

export type PublishVacancyApiV1VacanciesVacancyUuidPublishPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishVacancyApiV1VacanciesVacancyUuidPublishPostError = PublishVacancyApiV1VacanciesVacancyUuidPublishPostErrors[keyof PublishVacancyApiV1VacanciesVacancyUuidPublishPostErrors];

export type PublishVacancyApiV1VacanciesVacancyUuidPublishPostResponses = {
    /**
     * Successful Response
     */
    200: VacancyOut;
};

export type PublishVacancyApiV1VacanciesVacancyUuidPublishPostResponse = PublishVacancyApiV1VacanciesVacancyUuidPublishPostResponses[keyof PublishVacancyApiV1VacanciesVacancyUuidPublishPostResponses];

export type ArchiveVacancyApiV1VacanciesVacancyUuidArchivePostData = {
    body?: never;
    path: {
        /**
         * Vacancy Uuid
         */
        vacancy_uuid: string;
    };
    query?: never;
    url: '/api/v1/vacancies/{vacancy_uuid}/archive';
};

export type ArchiveVacancyApiV1VacanciesVacancyUuidArchivePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveVacancyApiV1VacanciesVacancyUuidArchivePostError = ArchiveVacancyApiV1VacanciesVacancyUuidArchivePostErrors[keyof ArchiveVacancyApiV1VacanciesVacancyUuidArchivePostErrors];

export type ArchiveVacancyApiV1VacanciesVacancyUuidArchivePostResponses = {
    /**
     * Successful Response
     */
    200: VacancyOut;
};

export type ArchiveVacancyApiV1VacanciesVacancyUuidArchivePostResponse = ArchiveVacancyApiV1VacanciesVacancyUuidArchivePostResponses[keyof ArchiveVacancyApiV1VacanciesVacancyUuidArchivePostResponses];

export type ModerateVacancyApiV1AdminVacanciesVacancyUuidModeratePostData = {
    body: ModerateIn;
    path: {
        /**
         * Vacancy Uuid
         */
        vacancy_uuid: string;
    };
    query?: never;
    url: '/api/v1/admin/vacancies/{vacancy_uuid}/moderate';
};

export type ModerateVacancyApiV1AdminVacanciesVacancyUuidModeratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ModerateVacancyApiV1AdminVacanciesVacancyUuidModeratePostError = ModerateVacancyApiV1AdminVacanciesVacancyUuidModeratePostErrors[keyof ModerateVacancyApiV1AdminVacanciesVacancyUuidModeratePostErrors];

export type ModerateVacancyApiV1AdminVacanciesVacancyUuidModeratePostResponses = {
    /**
     * Successful Response
     */
    200: VacancyOut;
};

export type ModerateVacancyApiV1AdminVacanciesVacancyUuidModeratePostResponse = ModerateVacancyApiV1AdminVacanciesVacancyUuidModeratePostResponses[keyof ModerateVacancyApiV1AdminVacanciesVacancyUuidModeratePostResponses];

export type VacancyApplicationsApiV1VacanciesVacancyUuidApplicationsGetData = {
    body?: never;
    path: {
        /**
         * Vacancy Uuid
         */
        vacancy_uuid: string;
    };
    query?: never;
    url: '/api/v1/vacancies/{vacancy_uuid}/applications';
};

export type VacancyApplicationsApiV1VacanciesVacancyUuidApplicationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VacancyApplicationsApiV1VacanciesVacancyUuidApplicationsGetError = VacancyApplicationsApiV1VacanciesVacancyUuidApplicationsGetErrors[keyof VacancyApplicationsApiV1VacanciesVacancyUuidApplicationsGetErrors];

export type VacancyApplicationsApiV1VacanciesVacancyUuidApplicationsGetResponses = {
    /**
     * Response Vacancy Applications Api V1 Vacancies  Vacancy Uuid  Applications Get
     * Successful Response
     */
    200: Array<CompanyApplicationOut>;
};

export type VacancyApplicationsApiV1VacanciesVacancyUuidApplicationsGetResponse = VacancyApplicationsApiV1VacanciesVacancyUuidApplicationsGetResponses[keyof VacancyApplicationsApiV1VacanciesVacancyUuidApplicationsGetResponses];

export type ApplyApiV1VacanciesVacancyUuidApplicationsPostData = {
    body?: never;
    path: {
        /**
         * Vacancy Uuid
         */
        vacancy_uuid: string;
    };
    query?: never;
    url: '/api/v1/vacancies/{vacancy_uuid}/applications';
};

export type ApplyApiV1VacanciesVacancyUuidApplicationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApplyApiV1VacanciesVacancyUuidApplicationsPostError = ApplyApiV1VacanciesVacancyUuidApplicationsPostErrors[keyof ApplyApiV1VacanciesVacancyUuidApplicationsPostErrors];

export type ApplyApiV1VacanciesVacancyUuidApplicationsPostResponses = {
    /**
     * Successful Response
     */
    201: ApplicationOut;
};

export type ApplyApiV1VacanciesVacancyUuidApplicationsPostResponse = ApplyApiV1VacanciesVacancyUuidApplicationsPostResponses[keyof ApplyApiV1VacanciesVacancyUuidApplicationsPostResponses];

export type MyApplicationsApiV1ApplicationsMyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/applications/my';
};

export type MyApplicationsApiV1ApplicationsMyGetResponses = {
    /**
     * Response My Applications Api V1 Applications My Get
     * Successful Response
     */
    200: Array<MyApplicationOut>;
};

export type MyApplicationsApiV1ApplicationsMyGetResponse = MyApplicationsApiV1ApplicationsMyGetResponses[keyof MyApplicationsApiV1ApplicationsMyGetResponses];

export type ApplicationDetailApiV1ApplicationsApplicationUuidGetData = {
    body?: never;
    path: {
        /**
         * Application Uuid
         */
        application_uuid: string;
    };
    query?: never;
    url: '/api/v1/applications/{application_uuid}';
};

export type ApplicationDetailApiV1ApplicationsApplicationUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApplicationDetailApiV1ApplicationsApplicationUuidGetError = ApplicationDetailApiV1ApplicationsApplicationUuidGetErrors[keyof ApplicationDetailApiV1ApplicationsApplicationUuidGetErrors];

export type ApplicationDetailApiV1ApplicationsApplicationUuidGetResponses = {
    /**
     * Successful Response
     */
    200: ApplicationDetailOut;
};

export type ApplicationDetailApiV1ApplicationsApplicationUuidGetResponse = ApplicationDetailApiV1ApplicationsApplicationUuidGetResponses[keyof ApplicationDetailApiV1ApplicationsApplicationUuidGetResponses];

export type ChangeStatusApiV1ApplicationsApplicationUuidStatusPostData = {
    body: StatusChangeIn;
    path: {
        /**
         * Application Uuid
         */
        application_uuid: string;
    };
    query?: never;
    url: '/api/v1/applications/{application_uuid}/status';
};

export type ChangeStatusApiV1ApplicationsApplicationUuidStatusPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeStatusApiV1ApplicationsApplicationUuidStatusPostError = ChangeStatusApiV1ApplicationsApplicationUuidStatusPostErrors[keyof ChangeStatusApiV1ApplicationsApplicationUuidStatusPostErrors];

export type ChangeStatusApiV1ApplicationsApplicationUuidStatusPostResponses = {
    /**
     * Successful Response
     */
    200: ApplicationOut;
};

export type ChangeStatusApiV1ApplicationsApplicationUuidStatusPostResponse = ChangeStatusApiV1ApplicationsApplicationUuidStatusPostResponses[keyof ChangeStatusApiV1ApplicationsApplicationUuidStatusPostResponses];

export type CompanyApplicationsApiV1CompaniesCompanyUuidApplicationsGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/applications';
};

export type CompanyApplicationsApiV1CompaniesCompanyUuidApplicationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompanyApplicationsApiV1CompaniesCompanyUuidApplicationsGetError = CompanyApplicationsApiV1CompaniesCompanyUuidApplicationsGetErrors[keyof CompanyApplicationsApiV1CompaniesCompanyUuidApplicationsGetErrors];

export type CompanyApplicationsApiV1CompaniesCompanyUuidApplicationsGetResponses = {
    /**
     * Response Company Applications Api V1 Companies  Company Uuid  Applications Get
     * Successful Response
     */
    200: Array<CompanyApplicationOut>;
};

export type CompanyApplicationsApiV1CompaniesCompanyUuidApplicationsGetResponse = CompanyApplicationsApiV1CompaniesCompanyUuidApplicationsGetResponses[keyof CompanyApplicationsApiV1CompaniesCompanyUuidApplicationsGetResponses];

export type ListCandidatesApiV1CompaniesCompanyUuidCandidatesGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: {
        /**
         * List
         */
        list?: 'shortlist' | 'reserve' | 'blacklist' | null;
    };
    url: '/api/v1/companies/{company_uuid}/candidates';
};

export type ListCandidatesApiV1CompaniesCompanyUuidCandidatesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCandidatesApiV1CompaniesCompanyUuidCandidatesGetError = ListCandidatesApiV1CompaniesCompanyUuidCandidatesGetErrors[keyof ListCandidatesApiV1CompaniesCompanyUuidCandidatesGetErrors];

export type ListCandidatesApiV1CompaniesCompanyUuidCandidatesGetResponses = {
    /**
     * Response List Candidates Api V1 Companies  Company Uuid  Candidates Get
     * Successful Response
     */
    200: Array<CandidateEntryOut>;
};

export type ListCandidatesApiV1CompaniesCompanyUuidCandidatesGetResponse = ListCandidatesApiV1CompaniesCompanyUuidCandidatesGetResponses[keyof ListCandidatesApiV1CompaniesCompanyUuidCandidatesGetResponses];

export type DeleteCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidDeleteData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
        /**
         * User Uuid
         */
        user_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/candidates/{user_uuid}';
};

export type DeleteCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidDeleteError = DeleteCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidDeleteErrors[keyof DeleteCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidDeleteErrors];

export type DeleteCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidDeleteResponse = DeleteCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidDeleteResponses[keyof DeleteCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidDeleteResponses];

export type PutCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidPutData = {
    body: CandidateEntryIn;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
        /**
         * User Uuid
         */
        user_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/candidates/{user_uuid}';
};

export type PutCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidPutError = PutCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidPutErrors[keyof PutCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidPutErrors];

export type PutCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidPutResponses = {
    /**
     * Successful Response
     */
    200: CandidateEntryOut;
};

export type PutCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidPutResponse = PutCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidPutResponses[keyof PutCandidateApiV1CompaniesCompanyUuidCandidatesUserUuidPutResponses];

export type ListTestsApiV1TestsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tests';
};

export type ListTestsApiV1TestsGetResponses = {
    /**
     * Response List Tests Api V1 Tests Get
     * Successful Response
     */
    200: Array<TestListItemOut>;
};

export type ListTestsApiV1TestsGetResponse = ListTestsApiV1TestsGetResponses[keyof ListTestsApiV1TestsGetResponses];

export type CompanyTestsApiV1CompaniesCompanyUuidTestsGetData = {
    body?: never;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/tests';
};

export type CompanyTestsApiV1CompaniesCompanyUuidTestsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompanyTestsApiV1CompaniesCompanyUuidTestsGetError = CompanyTestsApiV1CompaniesCompanyUuidTestsGetErrors[keyof CompanyTestsApiV1CompaniesCompanyUuidTestsGetErrors];

export type CompanyTestsApiV1CompaniesCompanyUuidTestsGetResponses = {
    /**
     * Response Company Tests Api V1 Companies  Company Uuid  Tests Get
     * Successful Response
     */
    200: Array<CompanyTestItemOut>;
};

export type CompanyTestsApiV1CompaniesCompanyUuidTestsGetResponse = CompanyTestsApiV1CompaniesCompanyUuidTestsGetResponses[keyof CompanyTestsApiV1CompaniesCompanyUuidTestsGetResponses];

export type CreateCompanyTestApiV1CompaniesCompanyUuidTestsPostData = {
    body: TestCreateIn;
    path: {
        /**
         * Company Uuid
         */
        company_uuid: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_uuid}/tests';
};

export type CreateCompanyTestApiV1CompaniesCompanyUuidTestsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCompanyTestApiV1CompaniesCompanyUuidTestsPostError = CreateCompanyTestApiV1CompaniesCompanyUuidTestsPostErrors[keyof CreateCompanyTestApiV1CompaniesCompanyUuidTestsPostErrors];

export type CreateCompanyTestApiV1CompaniesCompanyUuidTestsPostResponses = {
    /**
     * Successful Response
     */
    201: TestOut;
};

export type CreateCompanyTestApiV1CompaniesCompanyUuidTestsPostResponse = CreateCompanyTestApiV1CompaniesCompanyUuidTestsPostResponses[keyof CreateCompanyTestApiV1CompaniesCompanyUuidTestsPostResponses];

export type CreatePlatformTestApiV1AdminTestsPostData = {
    body: TestCreateIn;
    path?: never;
    query?: never;
    url: '/api/v1/admin/tests';
};

export type CreatePlatformTestApiV1AdminTestsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePlatformTestApiV1AdminTestsPostError = CreatePlatformTestApiV1AdminTestsPostErrors[keyof CreatePlatformTestApiV1AdminTestsPostErrors];

export type CreatePlatformTestApiV1AdminTestsPostResponses = {
    /**
     * Successful Response
     */
    201: TestOut;
};

export type CreatePlatformTestApiV1AdminTestsPostResponse = CreatePlatformTestApiV1AdminTestsPostResponses[keyof CreatePlatformTestApiV1AdminTestsPostResponses];

export type ModerateTestApiV1AdminTestsTestUuidModeratePostData = {
    body: ModerateIn;
    path: {
        /**
         * Test Uuid
         */
        test_uuid: string;
    };
    query?: never;
    url: '/api/v1/admin/tests/{test_uuid}/moderate';
};

export type ModerateTestApiV1AdminTestsTestUuidModeratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ModerateTestApiV1AdminTestsTestUuidModeratePostError = ModerateTestApiV1AdminTestsTestUuidModeratePostErrors[keyof ModerateTestApiV1AdminTestsTestUuidModeratePostErrors];

export type ModerateTestApiV1AdminTestsTestUuidModeratePostResponses = {
    /**
     * Successful Response
     */
    200: TestOut;
};

export type ModerateTestApiV1AdminTestsTestUuidModeratePostResponse = ModerateTestApiV1AdminTestsTestUuidModeratePostResponses[keyof ModerateTestApiV1AdminTestsTestUuidModeratePostResponses];

export type StartAttemptApiV1TestsTestUuidAttemptsPostData = {
    body?: never;
    path: {
        /**
         * Test Uuid
         */
        test_uuid: string;
    };
    query?: never;
    url: '/api/v1/tests/{test_uuid}/attempts';
};

export type StartAttemptApiV1TestsTestUuidAttemptsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartAttemptApiV1TestsTestUuidAttemptsPostError = StartAttemptApiV1TestsTestUuidAttemptsPostErrors[keyof StartAttemptApiV1TestsTestUuidAttemptsPostErrors];

export type StartAttemptApiV1TestsTestUuidAttemptsPostResponses = {
    /**
     * Successful Response
     */
    201: AttemptWithQuestionsOut;
};

export type StartAttemptApiV1TestsTestUuidAttemptsPostResponse = StartAttemptApiV1TestsTestUuidAttemptsPostResponses[keyof StartAttemptApiV1TestsTestUuidAttemptsPostResponses];

export type AnswerApiV1AttemptsAttemptUuidAnswersPostData = {
    body: AnswerIn;
    path: {
        /**
         * Attempt Uuid
         */
        attempt_uuid: string;
    };
    query?: never;
    url: '/api/v1/attempts/{attempt_uuid}/answers';
};

export type AnswerApiV1AttemptsAttemptUuidAnswersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnswerApiV1AttemptsAttemptUuidAnswersPostError = AnswerApiV1AttemptsAttemptUuidAnswersPostErrors[keyof AnswerApiV1AttemptsAttemptUuidAnswersPostErrors];

export type AnswerApiV1AttemptsAttemptUuidAnswersPostResponses = {
    /**
     * Successful Response
     */
    200: AttemptOut;
};

export type AnswerApiV1AttemptsAttemptUuidAnswersPostResponse = AnswerApiV1AttemptsAttemptUuidAnswersPostResponses[keyof AnswerApiV1AttemptsAttemptUuidAnswersPostResponses];

export type FinishAttemptApiV1AttemptsAttemptUuidFinishPostData = {
    body?: never;
    path: {
        /**
         * Attempt Uuid
         */
        attempt_uuid: string;
    };
    query?: never;
    url: '/api/v1/attempts/{attempt_uuid}/finish';
};

export type FinishAttemptApiV1AttemptsAttemptUuidFinishPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FinishAttemptApiV1AttemptsAttemptUuidFinishPostError = FinishAttemptApiV1AttemptsAttemptUuidFinishPostErrors[keyof FinishAttemptApiV1AttemptsAttemptUuidFinishPostErrors];

export type FinishAttemptApiV1AttemptsAttemptUuidFinishPostResponses = {
    /**
     * Successful Response
     */
    200: AttemptOut;
};

export type FinishAttemptApiV1AttemptsAttemptUuidFinishPostResponse = FinishAttemptApiV1AttemptsAttemptUuidFinishPostResponses[keyof FinishAttemptApiV1AttemptsAttemptUuidFinishPostResponses];

export type AbandonAttemptApiV1AttemptsAttemptUuidAbandonPostData = {
    body?: never;
    path: {
        /**
         * Attempt Uuid
         */
        attempt_uuid: string;
    };
    query?: never;
    url: '/api/v1/attempts/{attempt_uuid}/abandon';
};

export type AbandonAttemptApiV1AttemptsAttemptUuidAbandonPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AbandonAttemptApiV1AttemptsAttemptUuidAbandonPostError = AbandonAttemptApiV1AttemptsAttemptUuidAbandonPostErrors[keyof AbandonAttemptApiV1AttemptsAttemptUuidAbandonPostErrors];

export type AbandonAttemptApiV1AttemptsAttemptUuidAbandonPostResponses = {
    /**
     * Successful Response
     */
    200: AttemptOut;
};

export type AbandonAttemptApiV1AttemptsAttemptUuidAbandonPostResponse = AbandonAttemptApiV1AttemptsAttemptUuidAbandonPostResponses[keyof AbandonAttemptApiV1AttemptsAttemptUuidAbandonPostResponses];
