"""company: контакт заявителя (ФИО, email, должность)

Revision ID: 173366c76a8e
Revises: bcc9784a86dd
Create Date: 2026-07-05 21:14:01.958120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173366c76a8e'
down_revision: Union[str, Sequence[str], None] = 'bcc9784a86dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('contact_name', sa.String(length=200), nullable=False))
    op.add_column('company', sa.Column('contact_email', sa.String(length=254), nullable=False))
    op.add_column('company', sa.Column('contact_position', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'contact_position')
    op.drop_column('company', 'contact_email')
    op.drop_column('company', 'contact_name')
    # ### end Alembic commands ###
