"""test.materials + возобновление попытки

Revision ID: 17ece7973930
Revises: 173366c76a8e
Create Date: 2026-07-05 22:23:57.996928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ece7973930'
down_revision: Union[str, Sequence[str], None] = '173366c76a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('materials', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'materials')
    # ### end Alembic commands ###
