"""vacancy table

Revision ID: 1b925d29c976
Revises: 965a994d7bda
Create Date: 2026-07-02 22:12:49.653968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b925d29c976'
down_revision: Union[str, Sequence[str], None] = '965a994d7bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy',
    sa.Column('vacancy_uuid', sa.Uuid(), nullable=False),
    sa.Column('company_uuid', sa.Uuid(), nullable=False),
    sa.Column('filial_uuid', sa.Uuid(), nullable=False),
    sa.Column('created_by_uuid', sa.Uuid(), nullable=False),
    sa.Column('role_name', sa.String(length=80), nullable=False),
    sa.Column('event_title', sa.String(length=200), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue_address', sa.String(length=300), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('pay_hour_kop', sa.BigInteger(), nullable=False),
    sa.Column('pay_total_kop', sa.BigInteger(), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), server_default='{}', nullable=False),
    sa.Column('requirements', sa.ARRAY(sa.String(length=120)), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_moderation', 'active', 'rejected', 'done', name='vacancystatus', native_enum=False, length=20), nullable=False),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_uuid'], ['company.company_uuid'], name=op.f('fk_vacancy_company_uuid_company')),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['team_member.team_member_uuid'], name=op.f('fk_vacancy_created_by_uuid_team_member')),
    sa.ForeignKeyConstraint(['filial_uuid'], ['filial.filial_uuid'], name=op.f('fk_vacancy_filial_uuid_filial')),
    sa.PrimaryKeyConstraint('vacancy_uuid', name=op.f('pk_vacancy'))
    )
    op.create_index(op.f('ix_vacancy_company_uuid'), 'vacancy', ['company_uuid'], unique=False)
    op.create_index(op.f('ix_vacancy_status'), 'vacancy', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_status'), table_name='vacancy')
    op.drop_index(op.f('ix_vacancy_company_uuid'), table_name='vacancy')
    op.drop_table('vacancy')
    # ### end Alembic commands ###
