"""chat — треды и сообщения по заявкам

Revision ID: 2729e810ebe8
Revises: 9a65bc74bce9
Create Date: 2026-07-04 09:30:03.849499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2729e810ebe8'
down_revision: Union[str, Sequence[str], None] = '9a65bc74bce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_thread',
    sa.Column('chat_thread_uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('application_uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_uuid'], ['application.application_uuid'], name=op.f('fk_chat_thread_application_uuid_application')),
    sa.PrimaryKeyConstraint('chat_thread_uuid', name=op.f('pk_chat_thread')),
    sa.UniqueConstraint('application_uuid', name='uq_chat_thread_application')
    )
    op.create_index(op.f('ix_chat_thread_application_uuid'), 'chat_thread', ['application_uuid'], unique=False)
    op.create_table('chat_message',
    sa.Column('chat_message_uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('chat_thread_uuid', sa.Uuid(), nullable=False),
    sa.Column('sender_uuid', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_thread_uuid'], ['chat_thread.chat_thread_uuid'], name=op.f('fk_chat_message_chat_thread_uuid_chat_thread')),
    sa.ForeignKeyConstraint(['sender_uuid'], ['user.user_uuid'], name=op.f('fk_chat_message_sender_uuid_user')),
    sa.PrimaryKeyConstraint('chat_message_uuid', name=op.f('pk_chat_message'))
    )
    op.create_index(op.f('ix_chat_message_chat_thread_uuid'), 'chat_message', ['chat_thread_uuid'], unique=False)
    op.create_index(op.f('ix_chat_message_sender_uuid'), 'chat_message', ['sender_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_sender_uuid'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_chat_thread_uuid'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_chat_thread_application_uuid'), table_name='chat_thread')
    op.drop_table('chat_thread')
    # ### end Alembic commands ###
