"""email_message: журнал исходящих писем (§11.14)

Revision ID: 300ff0a7d34c
Revises: f9caade50bf0
Create Date: 2026-07-08 12:14:24.318147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300ff0a7d34c'
down_revision: Union[str, Sequence[str], None] = 'f9caade50bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_message',
    sa.Column('email_message_uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_uuid'], name=op.f('fk_email_message_created_by_user')),
    sa.PrimaryKeyConstraint('email_message_uuid', name=op.f('pk_email_message'))
    )
    op.create_index(op.f('ix_email_message_to_email'), 'email_message', ['to_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_message_to_email'), table_name='email_message')
    op.drop_table('email_message')
    # ### end Alembic commands ###
