"""user: moderation_status + модерация пользователя (§11.15)

Revision ID: 33c7e12b7a0e
Revises: 300ff0a7d34c
Create Date: 2026-07-23 19:26:45.002345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c7e12b7a0e'
down_revision: Union[str, Sequence[str], None] = '300ff0a7d34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('moderation_status', sa.Enum('pending', 'approved', 'resubmit', 'banned', name='moderationstatus', native_enum=False, length=20), server_default='pending', nullable=False))
    op.add_column('user', sa.Column('moderation_reason', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('moderated_by_uuid', sa.Uuid(), nullable=True))
    op.add_column('user', sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_user_moderated_by_uuid_user'), 'user', 'user', ['moderated_by_uuid'], ['user_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_moderated_by_uuid_user'), 'user', type_='foreignkey')
    op.drop_column('user', 'moderated_at')
    op.drop_column('user', 'moderated_by_uuid')
    op.drop_column('user', 'moderation_reason')
    op.drop_column('user', 'moderation_status')
    # ### end Alembic commands ###
