"""test.description + создание черновиком

Revision ID: 3625d01a7b0e
Revises: 6dc145e24b12
Create Date: 2026-07-05 12:58:55.086271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3625d01a7b0e'
down_revision: Union[str, Sequence[str], None] = '6dc145e24b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'description')
    # ### end Alembic commands ###
