"""vacancy.required_test_uuids — гейт откликов по тестам

Revision ID: 397604d923e8
Revises: 4770d223af01
Create Date: 2026-07-05 02:13:47.210802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397604d923e8'
down_revision: Union[str, Sequence[str], None] = '4770d223af01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('required_test_uuids', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'required_test_uuids')
    # ### end Alembic commands ###
