"""заявка организации: реквизиты, точка на карте, rejected, verified_at

Revision ID: 41a83b1a8550
Revises: 4772d479214c
Create Date: 2026-07-03 18:16:37.668933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a83b1a8550'
down_revision: Union[str, Sequence[str], None] = '4772d479214c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='' / 0 — backfill для компаний, созданных до появления заявки;
    # их реквизиты админ увидит пустыми и не подтвердит, пока владелец не переподаст заявку
    op.add_column('company', sa.Column('inn', sa.String(length=12), nullable=False, server_default=''))
    op.add_column('company', sa.Column('ogrn', sa.String(length=15), nullable=False, server_default=''))
    op.add_column('company', sa.Column('address', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('company', sa.Column('lat', sa.Float(), nullable=False, server_default='0'))
    op.add_column('company', sa.Column('lon', sa.Float(), nullable=False, server_default='0'))
    op.add_column('company', sa.Column('contact_phone', sa.String(length=16), nullable=False, server_default=''))
    for col in ('inn', 'ogrn', 'address', 'lat', 'lon', 'contact_phone'):
        op.alter_column('company', col, server_default=None)
    op.add_column('company', sa.Column('reject_reason', sa.String(length=500), nullable=True))
    op.add_column('company', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'verified_at')
    op.drop_column('company', 'reject_reason')
    op.drop_column('company', 'contact_phone')
    op.drop_column('company', 'lon')
    op.drop_column('company', 'lat')
    op.drop_column('company', 'address')
    op.drop_column('company', 'ogrn')
    op.drop_column('company', 'inn')
    # ### end Alembic commands ###
