"""user: email как логин (unique), phone nullable

Revision ID: 4770d223af01
Revises: 2729e810ebe8
Create Date: 2026-07-04 16:15:48.439805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4770d223af01'
down_revision: Union[str, Sequence[str], None] = '2729e810ebe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###
