"""uuidv7 server_default для всех PK

Revision ID: 4772d479214c
Revises: d72a817aaa56
Create Date: 2026-07-03 18:04:29.936749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4772d479214c'
down_revision: Union[str, Sequence[str], None] = 'd72a817aaa56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'account_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('application', 'application_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('application_event', 'application_event_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('candidate_list_entry', 'entry_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('company', 'company_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('document', 'document_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('filial', 'filial_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('invite_link', 'invite_link_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('ledger_entry', 'ledger_entry_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('team_member', 'team_member_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('test', 'test_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('test_attempt', 'test_attempt_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('test_question', 'test_question_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('topup_request', 'topup_request_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('user', 'user_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('vacancy', 'vacancy_uuid',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'vacancy_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'user_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('topup_request', 'topup_request_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('test_question', 'test_question_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('test_attempt', 'test_attempt_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('test', 'test_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_member', 'team_member_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ledger_entry', 'ledger_entry_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invite_link', 'invite_link_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('filial', 'filial_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('document', 'document_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('company', 'company_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('candidate_list_entry', 'entry_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('application_event', 'application_event_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('application', 'application_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('account', 'account_uuid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
