"""user.experience — опыт работы

Revision ID: 4fde2a25cb0e
Revises: 17ece7973930
Create Date: 2026-07-06 14:17:41.081887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fde2a25cb0e'
down_revision: Union[str, Sequence[str], None] = '17ece7973930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('experience', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'experience')
    # ### end Alembic commands ###
