"""company_favorite + notification

Revision ID: 6dc145e24b12
Revises: cb2f9d8e587a
Create Date: 2026-07-05 12:38:36.134652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc145e24b12'
down_revision: Union[str, Sequence[str], None] = 'cb2f9d8e587a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_favorite',
    sa.Column('company_favorite_uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('company_uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_uuid'], ['company.company_uuid'], name=op.f('fk_company_favorite_company_uuid_company')),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.user_uuid'], name=op.f('fk_company_favorite_user_uuid_user')),
    sa.PrimaryKeyConstraint('company_favorite_uuid', name=op.f('pk_company_favorite')),
    sa.UniqueConstraint('user_uuid', 'company_uuid', name='uq_favorite_user_company')
    )
    op.create_index(op.f('ix_company_favorite_company_uuid'), 'company_favorite', ['company_uuid'], unique=False)
    op.create_index(op.f('ix_company_favorite_user_uuid'), 'company_favorite', ['user_uuid'], unique=False)
    op.create_table('notification',
    sa.Column('notification_uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company_uuid', sa.Uuid(), nullable=True),
    sa.Column('vacancy_uuid', sa.Uuid(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_uuid'], ['company.company_uuid'], name=op.f('fk_notification_company_uuid_company')),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.user_uuid'], name=op.f('fk_notification_user_uuid_user')),
    sa.ForeignKeyConstraint(['vacancy_uuid'], ['vacancy.vacancy_uuid'], name=op.f('fk_notification_vacancy_uuid_vacancy')),
    sa.PrimaryKeyConstraint('notification_uuid', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_user_uuid'), 'notification', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_user_uuid'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_company_favorite_user_uuid'), table_name='company_favorite')
    op.drop_index(op.f('ix_company_favorite_company_uuid'), table_name='company_favorite')
    op.drop_table('company_favorite')
    # ### end Alembic commands ###
