"""service_price per-company + worker_completion

Revision ID: 764df088d728
Revises: 4fde2a25cb0e
Create Date: 2026-07-06 15:08:19.713561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764df088d728'
down_revision: Union[str, Sequence[str], None] = '4fde2a25cb0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_price', sa.Column('company_uuid', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_service_price_key'), table_name='service_price')
    op.create_index(op.f('ix_service_price_key'), 'service_price', ['key'], unique=False)
    op.create_index(op.f('ix_service_price_company_uuid'), 'service_price', ['company_uuid'], unique=False)
    op.create_unique_constraint('uq_service_price_key_company', 'service_price', ['key', 'company_uuid'])
    op.create_foreign_key(op.f('fk_service_price_company_uuid_company'), 'service_price', 'company', ['company_uuid'], ['company_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_service_price_company_uuid_company'), 'service_price', type_='foreignkey')
    op.drop_constraint('uq_service_price_key_company', 'service_price', type_='unique')
    op.drop_index(op.f('ix_service_price_company_uuid'), table_name='service_price')
    op.drop_index(op.f('ix_service_price_key'), table_name='service_price')
    op.create_index(op.f('ix_service_price_key'), 'service_price', ['key'], unique=True)
    op.drop_column('service_price', 'company_uuid')
    # ### end Alembic commands ###
