"""user: email и email_verified_at

Revision ID: 866eb183761e
Revises: 41a83b1a8550
Create Date: 2026-07-03 19:26:14.593800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866eb183761e'
down_revision: Union[str, Sequence[str], None] = '41a83b1a8550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=254), nullable=True))
    op.add_column('user', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified_at')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
