"""service_price — редактируемые тарифы услуг

Revision ID: 8e2461fcb2e9
Revises: 397604d923e8
Create Date: 2026-07-05 02:24:51.035147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2461fcb2e9'
down_revision: Union[str, Sequence[str], None] = '397604d923e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_price',
    sa.Column('service_price_uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('amount_kop', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('service_price_uuid', name=op.f('pk_service_price'))
    )
    op.create_index(op.f('ix_service_price_key'), 'service_price', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_price_key'), table_name='service_price')
    op.drop_table('service_price')
    # ### end Alembic commands ###
