"""account, ledger_entry, topup_request

Revision ID: 965a994d7bda
Revises: f5200bc1d1db
Create Date: 2026-07-02 17:27:49.978889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965a994d7bda'
down_revision: Union[str, Sequence[str], None] = 'f5200bc1d1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_uuid', sa.Uuid(), nullable=False),
    sa.Column('owner_type', sa.Enum('company', 'user', 'platform', name='accountownertype', native_enum=False, length=20), nullable=False),
    sa.Column('owner_uuid', sa.Uuid(), nullable=False),
    sa.Column('available_kop', sa.BigInteger(), nullable=False),
    sa.Column('on_hold_kop', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('account_uuid', name=op.f('pk_account')),
    sa.UniqueConstraint('owner_type', 'owner_uuid', name='uq_account_owner')
    )
    op.create_index(op.f('ix_account_owner_uuid'), 'account', ['owner_uuid'], unique=False)
    op.create_table('ledger_entry',
    sa.Column('ledger_entry_uuid', sa.Uuid(), nullable=False),
    sa.Column('debit_account_uuid', sa.Uuid(), nullable=False),
    sa.Column('credit_account_uuid', sa.Uuid(), nullable=False),
    sa.Column('amount_kop', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('topup', 'vacancy_fee', 'test_fee', 'hold', 'release', 'payout', 'commission', name='ledgerkind', native_enum=False, length=20), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=True),
    sa.Column('ref_uuid', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_kop > 0', name=op.f('ck_ledger_entry_amount_positive')),
    sa.CheckConstraint('debit_account_uuid <> credit_account_uuid', name=op.f('ck_ledger_entry_different_accounts')),
    sa.ForeignKeyConstraint(['credit_account_uuid'], ['account.account_uuid'], name=op.f('fk_ledger_entry_credit_account_uuid_account')),
    sa.ForeignKeyConstraint(['debit_account_uuid'], ['account.account_uuid'], name=op.f('fk_ledger_entry_debit_account_uuid_account')),
    sa.PrimaryKeyConstraint('ledger_entry_uuid', name=op.f('pk_ledger_entry'))
    )
    op.create_index(op.f('ix_ledger_entry_credit_account_uuid'), 'ledger_entry', ['credit_account_uuid'], unique=False)
    op.create_index(op.f('ix_ledger_entry_debit_account_uuid'), 'ledger_entry', ['debit_account_uuid'], unique=False)
    op.create_table('topup_request',
    sa.Column('topup_request_uuid', sa.Uuid(), nullable=False),
    sa.Column('account_uuid', sa.Uuid(), nullable=False),
    sa.Column('amount_kop', sa.BigInteger(), nullable=False),
    sa.Column('proof_document_uuid', sa.Uuid(), nullable=False),
    sa.Column('payment_details', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='topupstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reviewed_by_uuid', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_uuid'], ['account.account_uuid'], name=op.f('fk_topup_request_account_uuid_account')),
    sa.ForeignKeyConstraint(['proof_document_uuid'], ['document.document_uuid'], name=op.f('fk_topup_request_proof_document_uuid_document')),
    sa.ForeignKeyConstraint(['reviewed_by_uuid'], ['user.user_uuid'], name=op.f('fk_topup_request_reviewed_by_uuid_user')),
    sa.PrimaryKeyConstraint('topup_request_uuid', name=op.f('pk_topup_request'))
    )
    op.create_index(op.f('ix_topup_request_account_uuid'), 'topup_request', ['account_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topup_request_account_uuid'), table_name='topup_request')
    op.drop_table('topup_request')
    op.drop_index(op.f('ix_ledger_entry_debit_account_uuid'), table_name='ledger_entry')
    op.drop_index(op.f('ix_ledger_entry_credit_account_uuid'), table_name='ledger_entry')
    op.drop_table('ledger_entry')
    op.drop_index(op.f('ix_account_owner_uuid'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
