"""application, application_event, candidate_list_entry

Revision ID: 97435f16d4ab
Revises: 1b925d29c976
Create Date: 2026-07-02 22:30:32.163281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97435f16d4ab'
down_revision: Union[str, Sequence[str], None] = '1b925d29c976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_list_entry',
    sa.Column('entry_uuid', sa.Uuid(), nullable=False),
    sa.Column('company_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('list', sa.Enum('shortlist', 'reserve', 'blacklist', name='candidatelist', native_enum=False, length=20), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_uuid'], ['company.company_uuid'], name=op.f('fk_candidate_list_entry_company_uuid_company')),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.user_uuid'], name=op.f('fk_candidate_list_entry_user_uuid_user')),
    sa.PrimaryKeyConstraint('entry_uuid', name=op.f('pk_candidate_list_entry')),
    sa.UniqueConstraint('company_uuid', 'user_uuid', name='uq_candidate_entry_company_user')
    )
    op.create_index(op.f('ix_candidate_list_entry_company_uuid'), 'candidate_list_entry', ['company_uuid'], unique=False)
    op.create_index(op.f('ix_candidate_list_entry_user_uuid'), 'candidate_list_entry', ['user_uuid'], unique=False)
    op.create_table('application',
    sa.Column('application_uuid', sa.Uuid(), nullable=False),
    sa.Column('vacancy_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('review', 'confirmed', 'reserve', 'paid', 'done', name='applicationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.user_uuid'], name=op.f('fk_application_user_uuid_user')),
    sa.ForeignKeyConstraint(['vacancy_uuid'], ['vacancy.vacancy_uuid'], name=op.f('fk_application_vacancy_uuid_vacancy')),
    sa.PrimaryKeyConstraint('application_uuid', name=op.f('pk_application')),
    sa.UniqueConstraint('vacancy_uuid', 'user_uuid', name='uq_application_vacancy_user')
    )
    op.create_index(op.f('ix_application_user_uuid'), 'application', ['user_uuid'], unique=False)
    op.create_index(op.f('ix_application_vacancy_uuid'), 'application', ['vacancy_uuid'], unique=False)
    op.create_table('application_event',
    sa.Column('application_event_uuid', sa.Uuid(), nullable=False),
    sa.Column('application_uuid', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('applied', 'confirmed', 'shift', 'payout', name='applicationeventkind', native_enum=False, length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_uuid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['actor_uuid'], ['user.user_uuid'], name=op.f('fk_application_event_actor_uuid_user')),
    sa.ForeignKeyConstraint(['application_uuid'], ['application.application_uuid'], name=op.f('fk_application_event_application_uuid_application')),
    sa.PrimaryKeyConstraint('application_event_uuid', name=op.f('pk_application_event'))
    )
    op.create_index(op.f('ix_application_event_application_uuid'), 'application_event', ['application_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_event_application_uuid'), table_name='application_event')
    op.drop_table('application_event')
    op.drop_index(op.f('ix_application_vacancy_uuid'), table_name='application')
    op.drop_index(op.f('ix_application_user_uuid'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_candidate_list_entry_user_uuid'), table_name='candidate_list_entry')
    op.drop_index(op.f('ix_candidate_list_entry_company_uuid'), table_name='candidate_list_entry')
    op.drop_table('candidate_list_entry')
    # ### end Alembic commands ###
