"""complaint — жалобы участников

Revision ID: 9a65bc74bce9
Revises: 9b05f3cfe2c9
Create Date: 2026-07-04 01:32:16.136986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a65bc74bce9'
down_revision: Union[str, Sequence[str], None] = '9b05f3cfe2c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('complaint_uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('author_uuid', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('user', 'company', name='complainttargettype', native_enum=False, length=20), nullable=False),
    sa.Column('target_uuid', sa.Uuid(), nullable=False),
    sa.Column('vacancy_uuid', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='complaintseverity', native_enum=False, length=10), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', name='complaintstatus', native_enum=False, length=10), nullable=False),
    sa.Column('resolution', sa.String(length=1000), nullable=True),
    sa.Column('resolved_by_uuid', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_uuid'], ['user.user_uuid'], name=op.f('fk_complaint_author_uuid_user')),
    sa.ForeignKeyConstraint(['resolved_by_uuid'], ['user.user_uuid'], name=op.f('fk_complaint_resolved_by_uuid_user')),
    sa.ForeignKeyConstraint(['vacancy_uuid'], ['vacancy.vacancy_uuid'], name=op.f('fk_complaint_vacancy_uuid_vacancy')),
    sa.PrimaryKeyConstraint('complaint_uuid', name=op.f('pk_complaint'))
    )
    op.create_index(op.f('ix_complaint_author_uuid'), 'complaint', ['author_uuid'], unique=False)
    op.create_index(op.f('ix_complaint_target_uuid'), 'complaint', ['target_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_target_uuid'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_author_uuid'), table_name='complaint')
    op.drop_table('complaint')
    # ### end Alembic commands ###
