"""review — отзывы по завершённым заявкам

Revision ID: 9b05f3cfe2c9
Revises: fd68ae73cf0f
Create Date: 2026-07-04 01:30:21.915684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b05f3cfe2c9'
down_revision: Union[str, Sequence[str], None] = 'fd68ae73cf0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('review_uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('application_uuid', sa.Uuid(), nullable=False),
    sa.Column('vacancy_uuid', sa.Uuid(), nullable=False),
    sa.Column('author_uuid', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('user', 'company', name='reviewtargettype', native_enum=False, length=20), nullable=False),
    sa.Column('target_uuid', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('kind', sa.Enum('about_org', 'about_event', 'about_worker', name='reviewkind', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_review_rating_range')),
    sa.ForeignKeyConstraint(['application_uuid'], ['application.application_uuid'], name=op.f('fk_review_application_uuid_application')),
    sa.ForeignKeyConstraint(['author_uuid'], ['user.user_uuid'], name=op.f('fk_review_author_uuid_user')),
    sa.ForeignKeyConstraint(['vacancy_uuid'], ['vacancy.vacancy_uuid'], name=op.f('fk_review_vacancy_uuid_vacancy')),
    sa.PrimaryKeyConstraint('review_uuid', name=op.f('pk_review')),
    sa.UniqueConstraint('author_uuid', 'application_uuid', name='uq_review_author_application')
    )
    op.create_index(op.f('ix_review_application_uuid'), 'review', ['application_uuid'], unique=False)
    op.create_index(op.f('ix_review_author_uuid'), 'review', ['author_uuid'], unique=False)
    op.create_index(op.f('ix_review_target_uuid'), 'review', ['target_uuid'], unique=False)
    op.create_index(op.f('ix_review_vacancy_uuid'), 'review', ['vacancy_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_vacancy_uuid'), table_name='review')
    op.drop_index(op.f('ix_review_target_uuid'), table_name='review')
    op.drop_index(op.f('ix_review_author_uuid'), table_name='review')
    op.drop_index(op.f('ix_review_application_uuid'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
