"""chat: правка/удаление сообщений + ревизии; user: о себе, английский, образование

Revision ID: aadc4735fdb6
Revises: 764df088d728
Create Date: 2026-07-06 18:32:45.675075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aadc4735fdb6'
down_revision: Union[str, Sequence[str], None] = '764df088d728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message_revision',
    sa.Column('chat_message_revision_uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('chat_message_uuid', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('replaced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_uuid'], ['chat_message.chat_message_uuid'], name=op.f('fk_chat_message_revision_chat_message_uuid_chat_message')),
    sa.PrimaryKeyConstraint('chat_message_revision_uuid', name=op.f('pk_chat_message_revision'))
    )
    op.create_index(op.f('ix_chat_message_revision_chat_message_uuid'), 'chat_message_revision', ['chat_message_uuid'], unique=False)
    op.add_column('chat_message', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chat_message', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('about', sa.String(length=2000), nullable=True))
    op.add_column('user', sa.Column('english_level', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('education', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'education')
    op.drop_column('user', 'english_level')
    op.drop_column('user', 'about')
    op.drop_column('chat_message', 'deleted_at')
    op.drop_column('chat_message', 'edited_at')
    op.drop_index(op.f('ix_chat_message_revision_chat_message_uuid'), table_name='chat_message_revision')
    op.drop_table('chat_message_revision')
    # ### end Alembic commands ###
