"""company_application: публичная заявка на отель (§11.16)

Revision ID: acb74c163086
Revises: 33c7e12b7a0e
Create Date: 2026-07-23 19:40:27.879930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb74c163086'
down_revision: Union[str, Sequence[str], None] = '33c7e12b7a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_application',
    sa.Column('company_application_uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('ogrn', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('contact_phone', sa.String(length=16), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=False),
    sa.Column('contact_position', sa.String(length=120), nullable=False),
    sa.Column('upload_token', sa.String(length=64), nullable=False),
    sa.Column('proof_storage_key', sa.String(length=255), nullable=True),
    sa.Column('proof_mime', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='applicationstatus', native_enum=False, length=20), server_default='pending', nullable=False),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('company_uuid', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_uuid'], ['company.company_uuid'], name=op.f('fk_company_application_company_uuid_company')),
    sa.PrimaryKeyConstraint('company_application_uuid', name=op.f('pk_company_application'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_application')
    # ### end Alembic commands ###
