"""payment_account + topup.payment_account_uuid

Revision ID: bcc9784a86dd
Revises: 3625d01a7b0e
Create Date: 2026-07-05 13:16:40.427613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc9784a86dd'
down_revision: Union[str, Sequence[str], None] = '3625d01a7b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_account',
    sa.Column('payment_account_uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('requisites', sa.String(length=1000), nullable=False),
    sa.Column('monthly_limit_kop', sa.BigInteger(), nullable=False),
    sa.Column('is_priority', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('payment_account_uuid', name=op.f('pk_payment_account'))
    )
    op.add_column('topup_request', sa.Column('payment_account_uuid', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_topup_request_payment_account_uuid_payment_account'), 'topup_request', 'payment_account', ['payment_account_uuid'], ['payment_account_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_topup_request_payment_account_uuid_payment_account'), 'topup_request', type_='foreignkey')
    op.drop_column('topup_request', 'payment_account_uuid')
    op.drop_table('payment_account')
    # ### end Alembic commands ###
