"""vacancy.description — О событии

Revision ID: cb2f9d8e587a
Revises: 8e2461fcb2e9
Create Date: 2026-07-05 12:24:13.436720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2f9d8e587a'
down_revision: Union[str, Sequence[str], None] = '8e2461fcb2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('description', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'description')
    # ### end Alembic commands ###
