"""test, test_question, test_attempt

Revision ID: d72a817aaa56
Revises: 97435f16d4ab
Create Date: 2026-07-02 22:45:31.500138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd72a817aaa56'
down_revision: Union[str, Sequence[str], None] = '97435f16d4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_uuid', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('platform', 'company', name='testkind', native_enum=False, length=20), nullable=False),
    sa.Column('company_uuid', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('min_correct', sa.Integer(), nullable=False),
    sa.Column('price_kop', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_moderation', 'published', 'rejected', name='teststatus', native_enum=False, length=20), nullable=False),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_uuid'], ['company.company_uuid'], name=op.f('fk_test_company_uuid_company')),
    sa.PrimaryKeyConstraint('test_uuid', name=op.f('pk_test'))
    )
    op.create_index(op.f('ix_test_company_uuid'), 'test', ['company_uuid'], unique=False)
    op.create_index(op.f('ix_test_status'), 'test', ['status'], unique=False)
    op.create_table('test_attempt',
    sa.Column('test_attempt_uuid', sa.Uuid(), nullable=False),
    sa.Column('test_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'finished', 'abandoned', name='attemptstatus', native_enum=False, length=20), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('score_pct', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_uuid'], ['test.test_uuid'], name=op.f('fk_test_attempt_test_uuid_test')),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.user_uuid'], name=op.f('fk_test_attempt_user_uuid_user')),
    sa.PrimaryKeyConstraint('test_attempt_uuid', name=op.f('pk_test_attempt'))
    )
    op.create_index(op.f('ix_test_attempt_test_uuid'), 'test_attempt', ['test_uuid'], unique=False)
    op.create_index(op.f('ix_test_attempt_user_uuid'), 'test_attempt', ['user_uuid'], unique=False)
    op.create_table('test_question',
    sa.Column('test_question_uuid', sa.Uuid(), nullable=False),
    sa.Column('test_uuid', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('multi', sa.Boolean(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_indices', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_uuid'], ['test.test_uuid'], name=op.f('fk_test_question_test_uuid_test')),
    sa.PrimaryKeyConstraint('test_question_uuid', name=op.f('pk_test_question'))
    )
    op.create_index(op.f('ix_test_question_test_uuid'), 'test_question', ['test_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_question_test_uuid'), table_name='test_question')
    op.drop_table('test_question')
    op.drop_index(op.f('ix_test_attempt_user_uuid'), table_name='test_attempt')
    op.drop_index(op.f('ix_test_attempt_test_uuid'), table_name='test_attempt')
    op.drop_table('test_attempt')
    op.drop_index(op.f('ix_test_status'), table_name='test')
    op.drop_index(op.f('ix_test_company_uuid'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
