"""document table + user desired_roles

Revision ID: ee06ecd92a7c
Revises: 9e26d0763903
Create Date: 2026-07-02 14:33:31.039778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee06ecd92a7c'
down_revision: Union[str, Sequence[str], None] = '9e26d0763903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('document_uuid', sa.Uuid(), nullable=False),
    sa.Column('owner_uuid', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('passport', 'selfie_with_passport', 'medbook', 'diploma', 'payment_proof', name='documentkind', native_enum=False, length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'rejected', name='documentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('flag', sa.String(length=120), nullable=True),
    sa.Column('reviewed_by_uuid', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_uuid'], ['user.user_uuid'], name=op.f('fk_document_owner_uuid_user')),
    sa.ForeignKeyConstraint(['reviewed_by_uuid'], ['user.user_uuid'], name=op.f('fk_document_reviewed_by_uuid_user')),
    sa.PrimaryKeyConstraint('document_uuid', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_owner_uuid'), 'document', ['owner_uuid'], unique=False)
    op.add_column('user', sa.Column('desired_roles', sa.ARRAY(sa.String(length=50)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'desired_roles')
    op.drop_index(op.f('ix_document_owner_uuid'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
