"""company, filial, team_member

Revision ID: f379fab2d8cc
Revises: ee06ecd92a7c
Create Date: 2026-07-02 14:40:20.418124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f379fab2d8cc'
down_revision: Union[str, Sequence[str], None] = 'ee06ecd92a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('pending', 'verified', name='companystatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('company_uuid', name=op.f('pk_company'))
    )
    op.create_table('filial',
    sa.Column('filial_uuid', sa.Uuid(), nullable=False),
    sa.Column('company_uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_uuid'], ['company.company_uuid'], name=op.f('fk_filial_company_uuid_company')),
    sa.PrimaryKeyConstraint('filial_uuid', name=op.f('pk_filial'))
    )
    op.create_index(op.f('ix_filial_company_uuid'), 'filial', ['company_uuid'], unique=False)
    op.create_table('team_member',
    sa.Column('team_member_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('company_uuid', sa.Uuid(), nullable=False),
    sa.Column('filial_uuid', sa.Uuid(), nullable=True),
    sa.Column('company_role', sa.Enum('main_manager', 'manager', 'coordinator', 'staff', name='companyrole', native_enum=False, length=20), nullable=False),
    sa.Column('perm_create', sa.Boolean(), nullable=False),
    sa.Column('perm_hire', sa.Boolean(), nullable=False),
    sa.Column('perm_finance', sa.Boolean(), nullable=False),
    sa.Column('perm_invite', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_uuid'], ['company.company_uuid'], name=op.f('fk_team_member_company_uuid_company')),
    sa.ForeignKeyConstraint(['filial_uuid'], ['filial.filial_uuid'], name=op.f('fk_team_member_filial_uuid_filial')),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.user_uuid'], name=op.f('fk_team_member_user_uuid_user')),
    sa.PrimaryKeyConstraint('team_member_uuid', name=op.f('pk_team_member')),
    sa.UniqueConstraint('user_uuid', 'company_uuid', name='uq_team_member_user_company')
    )
    op.create_index(op.f('ix_team_member_company_uuid'), 'team_member', ['company_uuid'], unique=False)
    op.create_index(op.f('ix_team_member_user_uuid'), 'team_member', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_member_user_uuid'), table_name='team_member')
    op.drop_index(op.f('ix_team_member_company_uuid'), table_name='team_member')
    op.drop_table('team_member')
    op.drop_index(op.f('ix_filial_company_uuid'), table_name='filial')
    op.drop_table('filial')
    op.drop_table('company')
    # ### end Alembic commands ###
