"""invite_link table

Revision ID: f5200bc1d1db
Revises: f379fab2d8cc
Create Date: 2026-07-02 16:58:35.843615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5200bc1d1db'
down_revision: Union[str, Sequence[str], None] = 'f379fab2d8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_link',
    sa.Column('invite_link_uuid', sa.Uuid(), nullable=False),
    sa.Column('company_uuid', sa.Uuid(), nullable=False),
    sa.Column('filial_uuid', sa.Uuid(), nullable=True),
    sa.Column('company_role', sa.Enum('main_manager', 'manager', 'coordinator', 'staff', name='companyrole', native_enum=False, length=20), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_uuid'], ['company.company_uuid'], name=op.f('fk_invite_link_company_uuid_company')),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['team_member.team_member_uuid'], name=op.f('fk_invite_link_created_by_uuid_team_member')),
    sa.ForeignKeyConstraint(['filial_uuid'], ['filial.filial_uuid'], name=op.f('fk_invite_link_filial_uuid_filial')),
    sa.PrimaryKeyConstraint('invite_link_uuid', name=op.f('pk_invite_link')),
    sa.UniqueConstraint('code', name=op.f('uq_invite_link_code'))
    )
    op.create_index(op.f('ix_invite_link_company_uuid'), 'invite_link', ['company_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_link_company_uuid'), table_name='invite_link')
    op.drop_table('invite_link')
    # ### end Alembic commands ###
