"""user: telegram, дата рождения, гражданство, пол

Revision ID: f9caade50bf0
Revises: aadc4735fdb6
Create Date: 2026-07-06 19:52:26.846315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9caade50bf0'
down_revision: Union[str, Sequence[str], None] = 'aadc4735fdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('citizenship', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    op.drop_column('user', 'citizenship')
    op.drop_column('user', 'birth_date')
    op.drop_column('user', 'telegram')
    # ### end Alembic commands ###
