"""payout — заявки на выплату по сменам

Revision ID: fd68ae73cf0f
Revises: 866eb183761e
Create Date: 2026-07-04 01:16:13.432860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd68ae73cf0f'
down_revision: Union[str, Sequence[str], None] = '866eb183761e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout',
    sa.Column('payout_uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('vacancy_uuid', sa.Uuid(), nullable=False),
    sa.Column('company_uuid', sa.Uuid(), nullable=False),
    sa.Column('workers_count', sa.Integer(), nullable=False),
    sa.Column('amount_kop', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'paid', name='payoutstatus', native_enum=False, length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_uuid'], ['company.company_uuid'], name=op.f('fk_payout_company_uuid_company')),
    sa.ForeignKeyConstraint(['vacancy_uuid'], ['vacancy.vacancy_uuid'], name=op.f('fk_payout_vacancy_uuid_vacancy')),
    sa.PrimaryKeyConstraint('payout_uuid', name=op.f('pk_payout'))
    )
    op.create_index(op.f('ix_payout_company_uuid'), 'payout', ['company_uuid'], unique=False)
    op.create_index(op.f('ix_payout_vacancy_uuid'), 'payout', ['vacancy_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payout_vacancy_uuid'), table_name='payout')
    op.drop_index(op.f('ix_payout_company_uuid'), table_name='payout')
    op.drop_table('payout')
    # ### end Alembic commands ###
